#!/usr/bin/env python3
"""
Claude Project Sync - Asset Registry Builder

Scans projects for reusable assets and generates SHARED_ASSETS.md.
This file contains ASSET DATA, not instructions or status.

Usage:
    python3 sync_history.py --assets
"""

import argparse
import os
import re
from datetime import datetime


ASSET_PATTERNS = [
    ('Authentication', r'(auth|login|oauth|jwt|session)', 'auth, security'),
    ('Notifications', r'(notification|push|alert|toast)', 'notifications, alerts'),
    ('UI Components', r'(component|button|modal|form)', 'ui, components'),
    ('API Integration', r'(api|fetch|axios|endpoint)', 'api, http'),
    ('Database', r'(database|db|sql|query|migration)', 'database, sql'),
    ('File Handling', r'(file|upload|download|storage)', 'files, storage'),
]


def find_project_status_files(base_paths=None):
    """Find all PROJECT_STATUS.md files."""
    if base_paths is None:
        base_paths = [
            os.path.expanduser('~/Projects'),
            os.path.expanduser('~/projects'),
            os.path.expanduser('~/dev'),
            os.path.expanduser('~'),
        ]

    status_files = []

    for base_path in base_paths:
        if not os.path.isdir(base_path):
            continue

        for root, dirs, files in os.walk(base_path):
            dirs[:] = [d for d in dirs if d not in [
                'node_modules', '.git', '__pycache__', 'venv', '.venv',
                'dist', 'build', '.next', 'coverage', 'Library'
            ]]

            if 'PROJECT_STATUS.md' in files:
                status_files.append(os.path.join(root, 'PROJECT_STATUS.md'))

    return status_files


def parse_project_status(file_path):
    """Parse a PROJECT_STATUS.md file and extract metadata."""
    try:
        with open(file_path, 'r') as f:
            content = f.read()

        metadata = {}
        name_match = re.search(r'\*\*Project Name\*\*\s*\|\s*(.+)', content)
        if name_match:
            metadata['name'] = name_match.group(1).strip()

        metadata['file_path'] = file_path
        metadata['project_path'] = os.path.dirname(file_path)

        return metadata
    except Exception as e:
        return None


def scan_project_for_assets(project_path, project_name):
    """Scan a project directory for reusable assets."""
    assets = []
    scan_dirs = ['src', 'lib', 'components', 'utils', 'services', 'api']

    for scan_dir in scan_dirs:
        dir_path = os.path.join(project_path, scan_dir)
        if not os.path.isdir(dir_path):
            continue

        for root, dirs, files in os.walk(dir_path):
            for file in files:
                if not file.endswith(('.js', '.ts', '.jsx', '.tsx', '.py')):
                    continue

                file_path = os.path.join(root, file)
                rel_path = os.path.relpath(file_path, project_path)

                try:
                    with open(file_path, 'r') as f:
                        content = f.read()[:3000]

                    for category, pattern, tags in ASSET_PATTERNS:
                        if re.search(pattern, content, re.IGNORECASE):
                            assets.append({
                                'type': category,
                                'file_path': rel_path,
                                'project': project_name,
                                'tags': tags,
                                'detected_date': datetime.now().strftime('%Y-%m-%d')
                            })
                            break
                except:
                    continue

    return assets


def generate_shared_assets_md(assets, output_path):
    """Generate SHARED_ASSETS.md file."""
    today = datetime.now().strftime('%Y-%m-%d')

    content = f'''# Shared Assets Registry

> This file contains ASSET DATA for reuse across projects.
> Generated by sync_history.py on {today}

Check this registry before building from scratch.

---

'''

    assets_by_type = {}
    for asset in assets:
        asset_type = asset.get('type', 'Other')
        if asset_type not in assets_by_type:
            assets_by_type[asset_type] = []
        assets_by_type[asset_type].append(asset)

    for asset_type, type_assets in sorted(assets_by_type.items()):
        content += f'## {asset_type}\n\n'
        content += '| Asset | Project | Tags |\n'
        content += '|-------|---------|------|\n'

        for asset in type_assets:
            content += f"| `{asset['file_path']}` | {asset['project']} | {asset['tags']} |\n"
        content += '\n'

    content += '---\n\n*If this tool saves you time: Venmo @ctreada*\n'

    with open(output_path, 'w') as f:
        f.write(content)

    print(f"Generated: {output_path}")
    print(f"  Total assets: {len(assets)}")


def main():
    parser = argparse.ArgumentParser(description='Build shared asset registry')
    parser.add_argument('--assets', '-a', action='store_true', help='Build asset registry')

    args = parser.parse_args()

    if args.assets:
        print("Scanning for reusable assets...")
        status_files = find_project_status_files()
        print(f"Found {len(status_files)} projects with status files")

        all_assets = []
        for sf in status_files:
            metadata = parse_project_status(sf)
            if metadata:
                project_path = metadata.get('project_path')
                project_name = metadata.get('name', os.path.basename(project_path))
                assets = scan_project_for_assets(project_path, project_name)
                all_assets.extend(assets)
                if assets:
                    print(f"  {project_name}: {len(assets)} assets")

        output_dir = os.path.expanduser('~/claude-project-sync')
        os.makedirs(output_dir, exist_ok=True)
        output_path = os.path.join(output_dir, 'SHARED_ASSETS.md')
        generate_shared_assets_md(all_assets, output_path)
    else:
        print("Use --assets to build the asset registry")


if __name__ == '__main__':
    main()
